In [34]:
## Cleaning Summary

# The BankSim dataset was cleaned by removing extra quote marks from categorical values. 
# The dataset has no missing values, no infinite numeric values, and no duplicate rows. 
# The constant columns `zipcodeOri` and `zipMerchant` were removed because they contain only one unique value. 
# The final cleaned dataset contains 594,643 rows and 8 columns.

In [35]:
import pandas as pd
import numpy as np

In [36]:
banksim = pd.read_csv(
    "/Users/tejaljadhav/Desktop/UCD/Spring2026/Deep Learning/DL_Project/Dataset/bs140513_032310.csv"
)

banksim.head()

,step,customer,age,gender,zipcodeOri,merchant,zipMerchant,category,amount,fraud
0,0,'C1093826151','4','M','28007','M348934600','28007','es_transportation',4.55,0
1,0,'C352968107','2','M','28007','M348934600','28007','es_transportation',39.68,0
2,0,'C2054744914','4','F','28007','M1823072687','28007','es_transportation',26.89,0
3,0,'C1760612790','3','M','28007','M348934600','28007','es_transportation',17.25,0
4,0,'C757503768','5','M','28007','M348934600','28007','es_transportation',35.72,0

In [37]:
banksim.shape

(594643, 10)

In [38]:
banksim.columns

Index(['step', 'customer', 'age', 'gender', 'zipcodeOri', 'merchant',
       'zipMerchant', 'category', 'amount', 'fraud'],
      dtype='object')

In [39]:
banksim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594643 entries, 0 to 594642
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   step         594643 non-null  int64
 1   customer     594643 non-null  object
 2   age          594643 non-null  object
 3   gender       594643 non-null  object
 4   zipcodeOri   594643 non-null  object
 5   merchant     594643 non-null  object
 6   zipMerchant  594643 non-null  object
 7   category     594643 non-null  object
 8   amount       594643 non-null  float64
 9   fraud        594643 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 45.4+ MB

In [40]:
# To remove extra quote marks.
banksim_clean = banksim.copy()

for col in banksim_clean.select_dtypes(include="object").columns:
    banksim_clean[col] = banksim_clean[col].str.strip().str.strip("'")

banksim_clean.head()

,step,customer,age,gender,zipcodeOri,merchant,zipMerchant,category,amount,fraud
0,0,C1093826151,4,M,28007,M348934600,28007,es_transportation,4.55,0
1,0,C352968107,2,M,28007,M348934600,28007,es_transportation,39.68,0
2,0,C2054744914,4,F,28007,M1823072687,28007,es_transportation,26.89,0
3,0,C1760612790,3,M,28007,M348934600,28007,es_transportation,17.25,0
4,0,C757503768,5,M,28007,M348934600,28007,es_transportation,35.72,0

In [43]:
# To check missing values.
banksim_clean.isnull().sum()

step           0
customer       0
age            0
gender         0
zipcodeOri     0
merchant       0
zipMerchant    0
category       0
amount         0
fraud          0
dtype: int64

In [44]:
# To check missing values.

banksim_clean.isnull().sum().sum()

0

In [45]:
# To check infinite values.

numeric_cols = banksim_clean.select_dtypes(include=[np.number]).columns

np.isinf(banksim_clean[numeric_cols]).sum()

step      0
amount    0
fraud     0
dtype: int64

In [46]:
# To check duplicated

banksim_clean.duplicated().sum()

0

In [47]:
# If duplicate exists.
banksim_clean = banksim_clean.drop_duplicates().reset_index(drop=True)

In [48]:
# To check fraud distribution.
banksim_clean["fraud"].value_counts()

fraud
0    587443
1      7200
Name: count, dtype: int64

In [49]:
banksim_clean["fraud"].value_counts(normalize=True) * 100

fraud
0    98.789189
1     1.210811
Name: proportion, dtype: float64

In [50]:
# To check categorical values.
banksim_clean["age"].value_counts().sort_index()

age
0      2452
1     58131
2    187310
3    147131
4    109025
5     62642
6     26774
U      1178
Name: count, dtype: int64

In [51]:
banksim_clean["gender"].value_counts()

gender
F    324565
M    268385
E      1178
U       515
Name: count, dtype: int64

In [52]:
banksim_clean["category"].value_counts()

category
es_transportation        505119
es_food                   26254
es_health                 16133
es_wellnessandbeauty      15086
es_fashion                 6454
es_barsandrestaurants      6373
es_hyper                   6098
es_sportsandtoys           4002
es_tech                    2370
es_home                    1986
es_hotelservices           1744
es_otherservices            912
es_contents                 885
es_travel                   728
es_leisure                  499
Name: count, dtype: int64

In [53]:
# Check constant columns.
banksim_clean.nunique()

step             180
customer        4112
age                8
gender             4
zipcodeOri         1
merchant          50
zipMerchant        1
category          15
amount         23767
fraud              2
dtype: int64

In [54]:
# Since zipcodeOri and zipMerchant only have one value, dropping them.
banksim_clean = banksim_clean.drop(["zipcodeOri", "zipMerchant"], axis=1)

In [55]:
# Check numeric ranges
banksim_clean[["step", "amount", "fraud"]].describe()

                step         amount          fraud
count  594643.000000  594643.000000  594643.000000
mean       94.986827      37.890135       0.012108
std        51.053632     111.402831       0.109369
min         0.000000       0.000000       0.000000
25%        52.000000      13.740000       0.000000
50%        97.000000      26.900000       0.000000
75%       139.000000      42.540000       0.000000
max       179.000000    8329.960000       1.000000

In [56]:
(banksim_clean["amount"] < 0).sum()

0

In [57]:
(banksim_clean["amount"] == 0).sum()

52

In [58]:
# To check correlation.
banksim_clean[["step", "amount", "fraud"]].corr()

            step    amount     fraud
step    1.000000 -0.007961 -0.011898
amount -0.007961  1.000000  0.489967
fraud  -0.011898  0.489967  1.000000

In [59]:
# Save cleaned dataset.
banksim_clean.to_csv(
    "/Users/tejaljadhav/Desktop/UCD/Spring2026/Deep Learning/DL_Project/Dataset/banksim_cleaned.csv",
    index=False
)