In [19]:
## Cleaning Summary

# The credit card dataset had no missing or infinite values, and all features were numeric. 
# Exact duplicate rows were removed, reducing the dataset from 284,807 to 283,726 rows. 
# The cleaned dataset now has 473 fraud cases out of 283,726 transactions.

In [1]:
import pandas as pd
import numpy as np

In [2]:
creditcard = pd.read_csv("/Users/tejaljadhav/Desktop/UCD/Spring2026/Deep Learning/DL_Project/Dataset/creditcard.csv")
creditcard.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
creditcard.shape

(284807, 31)

In [4]:
creditcard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
numeric_cols = creditcard.select_dtypes(include=[np.number]).columns

np.isinf(creditcard[numeric_cols]).sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
creditcard.duplicated().sum()

1081

In [10]:
# To check class distribution before dropping duplicates
creditcard["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [11]:
creditcard["Class"].value_counts(normalize=True) * 100

Class
0    99.827251
1     0.172749
Name: proportion, dtype: float64

In [12]:
# To drop exact duplicates.
creditcard_clean = creditcard.drop_duplicates().reset_index(drop=True)

In [13]:
creditcard_clean.shape

(283726, 31)

In [14]:
creditcard_clean["Class"].value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [15]:
# To check ranges.
creditcard_clean[["Time", "Amount", "Class"]].describe()

                Time         Amount          Class
count  283726.000000  283726.000000  283726.000000
mean    94811.077600      88.472687       0.001667
std     47481.047891     250.399437       0.040796
min         0.000000       0.000000       0.000000
25%     54204.750000       5.600000       0.000000
50%     84692.500000      22.000000       0.000000
75%    139298.000000      77.510000       0.000000
max    172792.000000   25691.160000       1.000000

In [16]:
(creditcard_clean["Amount"] < 0).sum()

0

In [17]:
(creditcard_clean["Amount"] == 0).sum()

1808

In [18]:
creditcard_clean.to_csv(
    "/Users/tejaljadhav/Desktop/UCD/Spring2026/Deep Learning/DL_Project/Dataset/creditcard_cleaned.csv",
    index=False
)